### ISSUE TITLE
Debian Jessie 8.6: apt-get install get stucked

### ISSUE THREAD

**Issue by helen-fornazier** [GoogleCloudPlatform/compute-image-packages#358] opened 2016-11-18 19:15 UTC
Installing compute-image-packages from the http://packages.cloud.google.com/apt google-cloud-compute-jessie main with apt-get install gets stucked forever in:

`Created symlink from /etc/systemd/system/multi-user.target.wants/google-startup-scripts.service to /usr/lib/systemd/system/google-startup-scripts.service.`

System details:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.6 (jessie)
Release:	8.6
Codename:	jessie
```

How to reproduce:

```
sudo tee /etc/apt/sources.list.d/google-cloud.list << EOM
deb http://packages.cloud.google.com/apt google-cloud-compute-jessie main
deb http://packages.cloud.google.com/apt google-cloud-packages-archive-keyring-jessie main
EOM
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
sudo apt-get update
sudo apt-get install -y google-cloud-packages-archive-keyring
sudo apt-get install -y google-config-jessie google-compute-engine-jessie google-compute-engine-init-jessie
```

Full log:
```
$ ssh debian@192.168.122.186
debian@192.168.122.186's password: 

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Fri Nov 18 13:55:36 2016 from 192.168.122.1
debian@debian:~$ sudo tee /etc/apt/sources.list.d/google-cloud.list << EOM
> deb http://packages.cloud.google.com/apt google-cloud-compute-jessie main
> deb http://packages.cloud.google.com/apt google-cloud-packages-archive-keyring-jessie main
> EOM

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for debian: 
deb http://packages.cloud.google.com/apt google-cloud-compute-jessie main
deb http://packages.cloud.google.com/apt google-cloud-packages-archive-keyring-jessie main
debian@debian:~$ curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   663  100   663    0     0    971      0 --:--:-- --:--:-- --:--:--   970
OK
debian@debian:~$ sudo apt-get update
Hit http://security.debian.org jessie/updates InRelease
Hit http://security.debian.org jessie/updates/main Sources                                                                             
Hit http://security.debian.org jessie/updates/main amd64 Packages                  
Hit http://security.debian.org jessie/updates/main Translation-en                    
Ign http://ftp.us.debian.org jessie InRelease                         
Hit http://ftp.us.debian.org jessie-updates InRelease                
Get:1 http://packages.cloud.google.com google-cloud-compute-jessie InRelease [3,771 B]
Hit http://ftp.us.debian.org jessie Release.gpg                            
Hit http://ftp.us.debian.org jessie-updates/main Sources                   
Get:2 http://ftp.us.debian.org jessie-updates/main amd64 Packages/DiffIndex [6,424 B]
Get:3 http://packages.cloud.google.com google-cloud-packages-archive-keyring-jessie InRelease [3,853 B]
Get:4 http://ftp.us.debian.org jessie-updates/main Translation-en/DiffIndex [2,704 B]
Hit http://ftp.us.debian.org jessie Release                      
Get:5 http://packages.cloud.google.com google-cloud-compute-jessie/main amd64 Packages [717 B]
Hit http://ftp.us.debian.org jessie/main Sources                      
Hit http://ftp.us.debian.org jessie/main amd64 Packages       
Hit http://ftp.us.debian.org jessie/main Translation-en           
Get:6 http://packages.cloud.google.com google-cloud-packages-archive-keyring-jessie/main amd64 Packages [382 B]
Ign http://packages.cloud.google.com google-cloud-compute-jessie/main Translation-en_US
Ign http://packages.cloud.google.com google-cloud-compute-jessie/main Translation-en
Ign http://packages.cloud.google.com google-cloud-packages-archive-keyring-jessie/main Translation-en_US
Ign http://packages.cloud.google.com google-cloud-packages-archive-keyring-jessie/main Translation-en
Fetched 17.9 kB in 5s (3,521 B/s)
Reading package lists... Done
debian@debian:~$ sudo apt-get install -y google-cloud-packages-archive-keyring
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  google-cloud-packages-archive-keyring
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 1,654 B of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://packages.cloud.google.com/apt/ google-cloud-packages-archive-keyring-jessie/main google-cloud-packages-archive-keyring all 1.0-1 [1,654 B]
Fetched 1,654 B in 0s (4,312 B/s)                          
Selecting previously unselected package google-cloud-packages-archive-keyring.
(Reading database ... 133396 files and directories currently installed.)
Preparing to unpack .../google-cloud-packages-archive-keyring_1.0-1_all.deb ...
Unpacking google-cloud-packages-archive-keyring (1.0-1) ...
Setting up google-cloud-packages-archive-keyring (1.0-1) ...
debian@debian:~$ sudo apt-get install -y google-config-jessie google-compute-engine-jessie google-compute-engine-init-jessie
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  python-boto python-cffi python-cryptography python-ndg-httpsclient python-openssl python-ply python-pyasn1 python-pycparser python-requests python-setuptools python-urllib3
Suggested packages:
  python-dev python-cryptography-doc python-cryptography-vectors python-openssl-doc python-openssl-dbg python-ply-doc doc-base
The following NEW packages will be installed:
  google-compute-engine-init-jessie google-compute-engine-jessie google-config-jessie python-boto python-cffi python-cryptography python-ndg-httpsclient python-openssl python-ply python-pyasn1
  python-pycparser python-requests python-setuptools python-urllib3
0 upgraded, 14 newly installed, 0 to remove and 0 not upgraded.
Need to get 1,769 kB of archives.
After this operation, 9,594 kB of additional disk space will be used.
Get:1 http://ftp.us.debian.org/debian/ jessie/main python-urllib3 all 1.9.1-3 [55.4 kB]
Get:2 http://packages.cloud.google.com/apt/ google-cloud-compute-jessie/main google-compute-engine-jessie all 2.2.4-0.1475271803 [53.4 kB]
Get:3 http://ftp.us.debian.org/debian/ jessie/main python-requests all 2.4.3-6 [204 kB]      
Get:4 http://packages.cloud.google.com/apt/ google-cloud-compute-jessie/main google-config-jessie amd64 2.1.0-0.1475271817 [3,740 B]
Get:5 http://packages.cloud.google.com/apt/ google-cloud-compute-jessie/main google-compute-engine-init-jessie amd64 2.1.1-0.1475271826 [3,012 B]
Get:6 http://ftp.us.debian.org/debian/ jessie/main python-boto all 2.34.0-2 [703 kB]               
Get:7 http://ftp.us.debian.org/debian/ jessie/main python-ply all 3.4-5 [62.9 kB]
Get:8 http://ftp.us.debian.org/debian/ jessie/main python-pycparser all 2.10+dfsg-3 [58.8 kB]
Get:9 http://ftp.us.debian.org/debian/ jessie/main python-cffi amd64 0.8.6-1 [67.2 kB]
Get:10 http://ftp.us.debian.org/debian/ jessie/main python-cryptography amd64 0.6.1-1 [165 kB]
Get:11 http://ftp.us.debian.org/debian/ jessie/main python-openssl all 0.14-1 [81.1 kB]
Get:12 http://ftp.us.debian.org/debian/ jessie/main python-ndg-httpsclient all 0.3.2-1 [20.5 kB]
Get:13 http://ftp.us.debian.org/debian/ jessie/main python-pyasn1 all 0.1.7-1 [49.3 kB]
Get:14 http://ftp.us.debian.org/debian/ jessie/main python-setuptools all 5.5.1-1 [242 kB]
Fetched 1,769 kB in 3s (563 kB/s)       
Selecting previously unselected package python-urllib3.
(Reading database ... 133397 files and directories currently installed.)
Preparing to unpack .../python-urllib3_1.9.1-3_all.deb ...
Unpacking python-urllib3 (1.9.1-3) ...
Selecting previously unselected package python-requests.
Preparing to unpack .../python-requests_2.4.3-6_all.deb ...
Unpacking python-requests (2.4.3-6) ...
Selecting previously unselected package python-boto.
Preparing to unpack .../python-boto_2.34.0-2_all.deb ...
Unpacking python-boto (2.34.0-2) ...
Selecting previously unselected package python-ply.
Preparing to unpack .../python-ply_3.4-5_all.deb ...
Unpacking python-ply (3.4-5) ...
Selecting previously unselected package python-pycparser.
Preparing to unpack .../python-pycparser_2.10+dfsg-3_all.deb ...
Unpacking python-pycparser (2.10+dfsg-3) ...
Selecting previously unselected package python-cffi.
Preparing to unpack .../python-cffi_0.8.6-1_amd64.deb ...
Unpacking python-cffi (0.8.6-1) ...
Selecting previously unselected package python-cryptography.
Preparing to unpack .../python-cryptography_0.6.1-1_amd64.deb ...
Unpacking python-cryptography (0.6.1-1) ...
Selecting previously unselected package python-openssl.
Preparing to unpack .../python-openssl_0.14-1_all.deb ...
Unpacking python-openssl (0.14-1) ...
Selecting previously unselected package python-ndg-httpsclient.
Preparing to unpack .../python-ndg-httpsclient_0.3.2-1_all.deb ...
Unpacking python-ndg-httpsclient (0.3.2-1) ...
Selecting previously unselected package python-pyasn1.
Preparing to unpack .../python-pyasn1_0.1.7-1_all.deb ...
Unpacking python-pyasn1 (0.1.7-1) ...
Selecting previously unselected package python-setuptools.
Preparing to unpack .../python-setuptools_5.5.1-1_all.deb ...
Unpacking python-setuptools (5.5.1-1) ...
Selecting previously unselected package google-compute-engine-jessie.
Preparing to unpack .../google-compute-engine-jessie_2.2.4-0.1475271803_all.deb ...
Unpacking google-compute-engine-jessie (2.2.4-0.1475271803) ...
Selecting previously unselected package google-config-jessie.
Preparing to unpack .../google-config-jessie_2.1.0-0.1475271817_amd64.deb ...
Unpacking google-config-jessie (2.1.0-0.1475271817) ...
Selecting previously unselected package google-compute-engine-init-jessie.
Preparing to unpack .../google-compute-engine-init-jessie_2.1.1-0.1475271826_amd64.deb ...
Unpacking google-compute-engine-init-jessie (2.1.1-0.1475271826) ...
Processing triggers for man-db (2.7.0.2-5) ...
Setting up python-urllib3 (1.9.1-3) ...
Setting up python-requests (2.4.3-6) ...
Setting up python-boto (2.34.0-2) ...
Setting up python-ply (3.4-5) ...
Setting up python-pycparser (2.10+dfsg-3) ...
Setting up python-cffi (0.8.6-1) ...
Setting up python-cryptography (0.6.1-1) ...
Setting up python-openssl (0.14-1) ...
Setting up python-ndg-httpsclient (0.3.2-1) ...
Setting up python-pyasn1 (0.1.7-1) ...
Setting up python-setuptools (5.5.1-1) ...
Setting up google-config-jessie (2.1.0-0.1475271817) ...
Setting up google-compute-engine-jessie (2.2.4-0.1475271803) ...
Setting up google-compute-engine-init-jessie (2.1.1-0.1475271826) ...
Created symlink from /etc/systemd/system/multi-user.target.wants/google-accounts-daemon.service to /usr/lib/systemd/system/google-accounts-daemon.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/google-clock-skew-daemon.service to /usr/lib/systemd/system/google-clock-skew-daemon.service.
Created symlink from /etc/systemd/system/sshd.service.wants/google-instance-setup.service to /usr/lib/systemd/system/google-instance-setup.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/google-instance-setup.service to /usr/lib/systemd/system/google-instance-setup.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/google-ip-forwarding-daemon.service to /usr/lib/systemd/system/google-ip-forwarding-daemon.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/google-network-setup.service to /usr/lib/systemd/system/google-network-setup.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/google-shutdown-scripts.service to /usr/lib/systemd/system/google-shutdown-scripts.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/google-startup-scripts.service to /usr/lib/systemd/system/google-startup-scripts.service.

```

**Comment by zmarano** [comment] 2016-11-30 00:31
I'm going to guess the issue is actually with the postinst step after the systemd job:
https://github.com/GoogleCloudPlatform/compute-image-packages/blob/master/google_compute_engine_init/systemd/postinst.sh#L31

Are you running this on a GCE VM?

**Comment by helen-fornazier** [comment] 2016-11-30 00:59
No, I am running on a local qemu, I get this error on a fresh Debian install.

**Comment by sentkuri** [comment] 2017-06-27 10:44
Even I am facing the same issue

**Comment by zmarano** [comment] 2017-06-27 16:12
The issue is that you are trying to install these packages outside of GCE- which is not at this point supported unless you ignore the postinst errors. However, we are working on a packaging rewrite to deal with this problem and make these packages compliant with policy.

**Comment by zmarano** [comment] 2017-08-29 22:00
Although generally, we don't support this software on environments outside of GCE as it is entirely meant to integrate into GCE, this should be resolved with the new packages which are Debian policy compliant. See the updated [README](https://github.com/GoogleCloudPlatform/compute-image-packages#packaging).

**Closed by zmarano** 2017-08-29 22:00 UTC
