### ISSUE TITLE
New python3 google-accounts-daemon removes ssh key from ubuntu user

### ISSUE THREAD

**Issue by gottwald** [GoogleCloudPlatform/compute-image-packages#381] opened 2017-03-06 15:30 UTC
Since using a base image with the new python3 version of the google-accounts-daemon I'm observing a behavioral change to the old one:

We're building our own images on top of the official ubuntu xenial ones (currently `ubuntu-1604-xenial-v20170303`).
During our images build we throw a public key into the ubuntu user's authorized_keys file which should act as sort of a fallback and still give us access, should the google accounts daemon ever go wild and delete all our other users.
All other login users are configured through project metadata.

Since the use of the new google-accounts-daemon the `ubuntu` user `authorized_keys` files gets deleted.
I'm able to stably reconstruct the situation by building an image with the google-account-daemon disabled, logging in with the mentioned fallback key and starting it by hand:

```
root@test-base1604-node1:~# stat /home/ubuntu/.ssh/authorized_keys 
  File: '/home/ubuntu/.ssh/authorized_keys'
  Size: 8354      	Blocks: 24         IO Block: 4096   regular file
Device: 801h/2049d	Inode: 268920      Links: 1
Access: (0600/-rw-------)  Uid: ( 1000/  ubuntu)   Gid: ( 1000/  ubuntu)
Access: 2017-03-06 14:57:19.556000000 +0000
Modify: 2017-03-06 14:57:06.852000000 +0000
Change: 2017-03-06 14:57:06.852000000 +0000
 Birth: -

root@test-base1604-node1:~# systemctl start google-accounts-daemon.service 

root@test-base1604-node1:~# stat /home/ubuntu/.ssh/authorized_keys 
stat: cannot stat '/home/ubuntu/.ssh/authorized_keys': No such file or directory
```

There is no mentioning of the `ubuntu` user in the project or instance metadata.
So in my opinion this user should therefore not be touched by the google accounts daemon at all.

I also found this in the logs:
```
Mar 06 14:59:44 test-base1604-node1 google_accounts_daemon[2233]: google-accounts: INFO Removing user ubuntu.
```
Although the `ubuntu` user still exists.
Even starting the daemon in debug mode doesn't give me more information on why it decided to touch the `ubuntu` user, or why deletion failed.

**Comment by illfelder** [comment] 2017-03-06 18:05
/cc @OddBloke @gaughen 

I've looked into the issue and I think the root cause is cloud-init rather than the accounts daemon. It appears that cloud-init will attempt to set up the ubuntu user with the ssh returned by `get_public_ssh_keys` in [DataSourceGCE.py](https://www.apt-browse.org/browse/ubuntu/xenial/main/all/cloud-init/0.7.7~bzr1212-0ubuntu1/file/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceGCE.py). At initialization, your project and instance metadata is empty, so the file doesn't get populated at all (and appears like it's getting removed).

If I'm reading the cloud-init code properly, there are multiple issues here:
- Most important - this logic shouldn't be needed; access is provided from the accounts daemon.
- `DataSourceGCE.py` is looking for out of date keys (`sshKeys` in instance metadata is deprecated).
- The function is including keys that may be expired.
-  `/home/ubuntu/.ssh/authorized_keys` is never updated during the life of the instance.

We'll reach out to Canonical to address the issue.

**Comment by gaughen** [comment] 2017-03-22 00:33
I suggest the next step is to file a bug against cloud-init (https://bugs.launchpad.net/ubuntu/+source/cloud-init/)

**Comment by gottwald** [comment] 2017-03-22 07:56
I have a bit of a hard time understanding why this is a cloud-init issue rather than a google-accounts-daemon issue.
The ubuntu user setup is perfectly fine when I don't start the google-accounts-daemon and leave cloud-init running.
I started the google-accounts-daemon by hand and verified with strace that it really does do a `unlink("/home/ubuntu/.ssh/authorized_keys") = 0`.
So I guess my question is, why you think it is a cloud-init problem when the google-accounts-daemon touches a user that it's not responsible for?
We don't have any instance or project metadata that should cause the accounts-daemon to touch the ubuntu user. All user-key combinations in metadata are 100% personalized.

**Comment by zmarano** [comment] 2017-03-29 23:35
Hi Ingo,
So far the only way I have been able to reproduce this (and what fits with the code as well) is to have an "ubuntu" user in metadata. If you delete the SSH key for that user the authorized_keys file also gets deleted (as intended). However, without that user in metadata, the authorized_keys file is left alone no matter what I do.

The log line you mentioned is what gets logged if via metadata an ubuntu user was removed so that fits the accounts daemon modifying that user. However, it doesn't modify users that are not in metadata. Cloud-init also modifies that file when the image is used on a new instance (but not on the same instance). But in my tests so far, it has not deleted the key I manually added- it only appends.

A couple follow up questions:
- Do you have some automation around setting up the instance that could be modifying the keys in metadata at all?
- How are you adding the ubuntu user ssh key on the image you are creating?

**Comment by gottwald** [comment] 2017-03-30 13:12
I know now what causes it, but not exactly why.
Looks like google-accounts-daemon is really not the problem here.

When I start an image without the accounts-daemon enabled there is already a ubuntu user listed in the file `/var/lib/google/google_users`.
If I start the google-accounts-daemon then it compares the users from metadata (which does not include an ubuntu user) and the one in the file and obviously comes to the conclusion that the ubuntu user needs to be removed because it's not in the metadata.

Looks like the `/var/lib/google/google_users` is a leftover from the imaging process with packer where the ubuntu user is used as provisioning user and its key is inserted via metadata during the build process.

Which still makes me wonder why this has ever worked that way? So either there was some behavior change of how packer gets the key on the system, which I can't find anything obvious in the packer code for, or something else has changed.

Either way, at least I can include a quick fix in our build job.
So as far as I'm concerned this can be closed.
Thx for your hints!

**Comment by illfelder** [comment] 2017-03-30 16:36
The file '/var/lib/google/google_users' was added as part of the new guest environment to ensure that the account daemon only modifies the users it manages. That's probably what you didn't run into that issue in the past.

Thanks for the update - I'll close this off.

**Closed by illfelder** 2017-03-30 16:36 UTC
