### ISSUE TITLE
When compute-image-packages get updated, vm instance's host key will get reset

### ISSUE THREAD

**Issue by githubwua** [GoogleCloudPlatform/compute-image-packages#310] opened 2016-07-22 02:26 UTC
In this commit, 

https://github.com/GoogleCloudPlatform/compute-image-packages/commit/5a249e940b1799633f6299d0772980697189af3a

The following code change is added:

google_compute_engine_init/sysvinit/rpm_replace
+# Replace existing guest.
+
+# Run instance setup.
+/usr/bin/google_instance_setup

When yum autoupdate applies this change, it runs google_instance_setup as a result.  This appears to reset the host key inadvertently.
(see: https://github.com/GoogleCloudPlatform/compute-image-packages/blob/master/README.md#instance-setup)

When the host key is reset, SSH to the VM instance will fail with the following warning:

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

And the old host key must be removed from ~/.ssh/known_hosts in order to connect.

Is it really necessary to run instance_setup whenever the compute-image-packages get updated?

**Comment by illfelder** [comment] 2016-07-22 02:33
instance_setup writes your instance ID to the instance_config.cfg file. If the instance ID has not changed, regenerate host keys should not be called. In the initial package we released for the new guest environment, there was a bug where the first update would trigger regenerate host keys, but that should not be true anymore.

**Comment by illfelder** [comment] 2016-07-22 03:16
I verified the correct behavior on a CentOS 6 instance using the following procedure:
-   Created a VM running an old version of the `google-compute-engine-init` package.
-   Ran the command `yum update`.
The `google-compute-engine` and `google-compute-engine-init` packages were both updated, and the host keys were not regenerated. 

I'm closing this off because the issue is fixed in the newer packages, but sorry for the inconvenience of a the bug in the older version.

**Closed by illfelder** 2016-07-22 03:16 UTC
