### ISSUE TITLE
When configured with a project SSH key, ubuntu user removed from all non-user groups

### ISSUE THREAD

**Issue by OddBloke** [GoogleCloudPlatform/compute-image-packages#326] opened 2016-08-22 12:37 UTC
I'm testing the new compute-image-packages in Ubuntu and I'm seeing that the `ubuntu` user will have its groups removed iff it is configured with an SSH key in project metadata.

**Steps to Reproduce**

1. Configure an SSH key for the `ubuntu` user at https://console.cloud.google.com/compute/metadata/sshKeys
2. Launch my test image in that project:

        gcloud compute instances create reproducer-$(date +%y%m%d-%H%M) --image daily-ubuntu-testing-1610-yakkety-v20160821 --image-project ubuntu-os-cloud-devel

3. SSH in as the `ubuntu` user, and run `groups`.

**Expected Behaviour**

`ubuntu` user is in the groups configured by cloud-init:

    $ groups
    ubuntu adm dialout cdrom floppy sudo audio dip video plugdev netdev lxd

**Actual Behaviour**

`ubuntu` user has only its own group:

        $ groups
        ubuntu

**Extra Info**

You can observe that `ubuntu` is removed from the groups in `/var/log/auth.log`:

    Aug 22 12:30:28 ubuntu usermod[2652]: delete 'ubuntu' from group 'adm'
    Aug 22 12:30:28 ubuntu usermod[2652]: delete 'ubuntu' from group 'dialout'
    ...

**Comment by OddBloke** [comment] 2016-08-22 12:39
I've spent a bit of time trying to work out what's going on, but ultimately ended up stymied.

**Comment by OddBloke** [comment] 2016-08-22 12:42
(Oh, a semi-expected behaviour would be to end up with the groups configured in `/etc/default/instance_configs.cfg`, but that didn't happen either ^_^)

**Comment by illfelder** [comment] 2016-08-22 18:48
Thanks for filing this! The issue isn't with the ubuntu user, but is an issue with the accounts daemon setting groups for users on Python 3. The issue is that the filter function returns an iterator in Python 3 (instead of a list). I'm making a patch to fix the issue.

**Comment by illfelder** [comment] 2016-08-22 18:50
Fixed in #327

**Comment by illfelder** [comment] 2016-08-22 18:53
This issue was not caught because the unit test called "sorted" on the filter response, and the sorted function converted the iterator to a sorted list.

**Comment by illfelder** [comment] 2016-08-23 13:08
The issue is fixed in our updated prerelease. Closing this off.

**Closed by illfelder** 2016-08-23 13:08 UTC
